name = "RowEchelon"
uuid = "af85af4c-bcd5-5d23-b03a-a909639aa875"
repo = "https://github.com/blegat/RowEchelon.jl.git"
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
